apiVersion: cdi.kubevirt.io/v1beta1
kind: VolumeImportSource
metadata:
  name: database-vm-import-source
spec:
  source:
    url: 'http://s3.us-east.cloud-object-storage.appdomain.cloud/roadshowocpvirt/database.qcow2'
