# WIP
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: user6-project
  namespace: openshift-gitops
spec:
  roles:
  - name: admin
    description: Read-only privileges to my-project
    policies:
    - p, proj:my-project:read-only, applications, get, my-project/*, allow
    groups:
    - user6