apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: database-vm-import-source
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi