apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: database
  name: database
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: database
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            bios: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      volumes:
      - persistentVolumeClaim:
            claimName: database
        name: rootdisk
