apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- database-disk.yaml
- database-vm.yaml
- winweb01-disk.yaml
- winweb01-vm.yaml
- winweb02-disk.yaml
- winweb02-vm.yaml
# Challenge TODO: add challenge resources