apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winweb01
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: winweb01-vm-import-source
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 25Gi